const {
  RACE_ITEMS_FFA,
  RACE_ITEMS_DUOS,
  RACE_ITEMS_3V3,
  RACE_ITEMS_4V4,
  RACE_SURVIVAL,
  RACE_ITEMLESS_1V1,
  RACE_ITEMLESS_FFA,
  RACE_ITEMLESS_DUOS,
  RACE_ITEMLESS_3V3,
  RACE_ITEMLESS_4V4,
  BATTLE_1V1,
  BATTLE_FFA,
  BATTLE_DUOS,
  BATTLE_3V3,
  BATTLE_4V4,
  INSTA_DUOS,
  INSTA_3V3,
  INSTA_4V4,
} = require('./models/lobby');

module.exports.lobbyTypes = [
  {
    key: RACE_ITEMS_FFA,
    name: 'FFA',
    description: null,
    emote: null,
    default: true,
  },
  {
    key: RACE_ITEMS_DUOS,
    name: 'Duos',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMS_3V3,
    name: '3 vs. 3',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMS_4V4,
    name: '4 vs. 4',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_SURVIVAL,
    name: 'Survival',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_1V1,
    name: 'Itemless 1 vs. 1',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_FFA,
    name: 'Itemless FFA',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_DUOS,
    name: 'Itemless Duos',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_3V3,
    name: 'Itemless 3 vs. 3',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_4V4,
    name: 'Itemless 4 vs. 4',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: BATTLE_1V1,
    name: 'Battle 1 vs. 1',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: BATTLE_FFA,
    name: 'Battle FFA',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: BATTLE_DUOS,
    name: 'Battle Duos',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: BATTLE_3V3,
    name: 'Battle 3 vs. 3',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: BATTLE_4V4,
    name: 'Battle 4 vs. 4',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: INSTA_DUOS,
    name: 'Insta Duos',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: INSTA_3V3,
    name: 'Insta 3 vs. 3',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: INSTA_4V4,
    name: 'Insta 4 vs. 4',
    description: null,
    emote: null,
    default: false,
  },
];
