module.exports.rulesets = [
  {
    id: 0,
    key: 'ur',
    name: 'Unrestricted',
    description: 'All speed tech and skips are allowed.',
    emote: '🔓',
    default: false,
    rankedEnabled: true,
  },
  {
    id: 1,
    key: 'def',
    name: 'Standard',
    description: 'The default ruleset for tournaments and ranked.',
    emote: '⚖️',
    default: true,
    rankedEnabled: true,
  },
  {
    id: 2,
    key: 'nmg',
    name: 'No Major Glitches',
    description: 'Some skips and the SE Polswid technique are banned.',
    emote: '🚫',
    default: true,
    rankedEnabled: true,
  },
  {
    id: 3,
    key: 'exp',
    name: 'Experimental',
    description: 'Dare trying it?',
    emote: '🧪',
    default: false,
    rankedEnabled: true,
  },
  {
    id: 4,
    key: 'ag',
    name: 'Anything Goes',
    description: 'Rules stop existing after the light goes green.',
    emote: '♾️',
    default: false,
    rankedEnabled: false,
  },
];
