module.exports.serverLanguages = [
  {
    key: ':flag_gb:',
    name: 'English',
    description: null,
    emote: '🇬🇧',
    default: true,
  },
  {
    key: ':flag_es:',
    name: 'Spanish',
    description: null,
    emote: '🇪🇸',
    default: true,
  },
  {
    key: ':flag_it:',
    name: 'Italian',
    description: null,
    emote: '🇮🇹',
    default: true,
  },
  {
    key: ':flag_fi:',
    name: 'Finnish',
    description: null,
    emote: '🇫🇮',
    default: true,
  },
  {
    key: ':flag_sa:',
    name: 'Arabic',
    description: null,
    emote: '🇸🇦',
    default: true,
  },
  {
    key: ':flag_jp:',
    name: 'Japanese',
    description: null,
    emote: '🇯🇵',
    default: true,
  },
  {
    key: ':flag_de:',
    name: 'German',
    description: null,
    emote: '🇩🇪',
    default: true,
  },
  {
    key: ':flag_pl:',
    name: 'Polish',
    description: null,
    emote: '🇵🇱',
    default: true,
  },
  {
    key: ':flag_fr:',
    name: 'French',
    description: null,
    emote: '🇫🇷',
    default: true,
  },
  {
    key: ':flag_pt:',
    name: 'Portuguese',
    description: null,
    emote: '🇵🇹',
    default: true,
  },
];
