module.exports.itemTiers = [
  {
    key: 'tier1',
    name: 'Tier 1',
    description: null,
    emote: null,
    default: false,
    minRank: 0,
    maxRank: 400,
  },
  {
    key: 'tier2',
    name: 'Tier 2',
    description: null,
    emote: null,
    default: false,
    minRank: 400,
    maxRank: 800,
  },
  {
    key: 'tier3',
    name: 'Tier 3',
    description: null,
    emote: null,
    default: false,
    minRank: 800,
    maxRank: 1200,
  },
  {
    key: 'tier4',
    name: 'Tier 4',
    description: null,
    emote: null,
    default: false,
    minRank: 1200,
    maxRank: 1600,
  },
  {
    key: 'tier5',
    name: 'Tier 5',
    description: null,
    emote: null,
    default: false,
    minRank: 1600,
    maxRank: 2000,
  },
  {
    key: 'tier6',
    name: 'Tier 6',
    description: null,
    emote: null,
    default: false,
    minRank: 2000,
    maxRank: 2400,
  },
  {
    key: 'tier7',
    name: 'Tier 7',
    description: null,
    emote: null,
    default: false,
    minRank: 2400,
    maxRank: 10000,
  },
];
