module.exports.trackOptions = [
  {
    key: 'random',
    name: 'Full RNG Tracks',
    description: 'Generates tracks completely at random.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'pools',
    name: 'Track Pools',
    description: 'Generates tracks from balanced track pools.',
    emote: null,
    default: true,
    rankedEnabled: true,
  },
  {
    key: 'draft',
    name: 'Track Drafting',
    description: 'Initializes a draft as soon as the lobby starts.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'bonus',
    name: 'Bonus Tracks',
    description: 'This list contains GP tracks + Retro Stadium.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'blue_fire',
    name: 'Blue Fire Tracks',
    description: 'This list contains blue fire tracks.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'cnk',
    name: 'CNK Tracks',
    description: 'This list contains tracks from CNK.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'ctr',
    name: 'CTR Tracks',
    description: 'This list contains tracks from the original CTR.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'day_time',
    name: 'Day Time Tracks',
    description: 'This list contains day time tracks.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'long',
    name: 'Long Tracks',
    description: 'This list contains tracks longer than 1:45 min.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'nature',
    name: 'Nature Tracks',
    description: 'This list contains tracks of natural environments.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'night_time',
    name: 'Night Time Tracks',
    description: 'This list contains night time tracks.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'polswid',
    name: 'Polswid Tracks',
    description: 'This list contains tracks with strong SGs.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'road',
    name: 'Road Tracks',
    description: 'This list contains tracks without offroad parts.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'sacred_fire',
    name: 'Sacred Fire Tracks',
    description: 'This list contains tracks without blue fire pads.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'small',
    name: 'Small Tracks',
    description: 'This list contains tracks shorter than 1:30 min.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
  {
    key: 'static',
    name: 'Static Tracks',
    description: 'This list contains tracks without moving hazards.',
    emote: null,
    default: false,
    rankedEnabled: true,
  },
];
