module.exports = [
  [
    'Turbo Track',
    'Polar Pass',
    'N. Gin Labs',
    'Cortex Castle',
    'Hot Air Skyway',
    'Oxide Station',
    'Clockwork Wumpa',
    'Electron Avenue',
    'Deep Sea Driving',
    'Tiny Temple',
    'Thunder Struck',
    'Out of Time',
    'Hyper Spaceway',
    'Twilight Tour',
    'Prehistoric Playground',
    'Nina\'s Nightmare',
    'Koala Carnival',
    'Gingerbread Joyride',
    'Megamix Mania',
    'Drive-Thru Danger',
  ],
];
