module.exports = [
  [
    'Mystery Caves',
    'Tiny Arena',
    'Polar Pass',
    'N. Gin Labs',
    'Cortex Castle',
    'Hot Air Skyway',
    'Oxide Station',
    'Clockwork Wumpa',
    'Android Alley',
    'Electron Avenue',
    'Thunder Struck',
    'Out of Time',
    'Assembly Lane',
    'Twilight Tour',
    'Prehistoric Playground',
    'Spyro Circuit',
    'Gingerbread Joyride',
    'Megamix Mania',
  ],
];
