module.exports = [
  [
    'Crash Cove',
    'Sewer Speedway',
    'Tiny Arena',
    'Polar Pass',
    'N. Gin Labs',
    'Cortex Castle',
    'Hot Air Skyway',
    'Oxide Station',
    'Inferno Island',
    'Clockwork Wumpa',
    'Android Alley',
    'Tiny Temple',
    'Thunder Struck',
    'Electron Avenue',
    'Assembly Lane',
    'Barin Ruins',
    'Hyper Spaceway',
    'Twilight Tour',
    'Prehistoric Playground',
    'Spyro Circuit',
    'Drive-Thru Danger',
  ],
];
